baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft 5 Matrix bug'
primary: true
siteGroup: 870dca90-bf34-4aaa-99e9-7de9beb15c7c # Craft 5 Matrix bug
sortOrder: 1
